name: 'Release-Go-Binary'

on:
  workflow_dispatch:
  release:
    types: ['created']

jobs:
  Release-Go-Binary:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v4'
    - name: 'Build'
      uses: 'lslqtz/go-release-action@t'
      id: release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: 'linux'
        goarch: 'amd64'
        goversion: 1.19
        md5sum: false
        sha256sum: false
        binary_name: 'go-testproject'
        extra_files: 'README.md'
        post_command: echo "echo {RELEASE_ASSET_DIR}, {RELEASE_ASSET_ARCHIVE_DIR}, {RELEASE_ASSET_NAME}, {RELEASE_ASSET_FILE}, {RELEASE_ASSET_PATH}"
    - name: 'Echo outputs'
      run: echo ${{join(steps.release.outputs.*, ', ')}}
    - name: 'Upload GitHub Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.release.outputs.release_asset_name }}
        path: ${{ steps.release.outputs.release_asset_dir }}/
