name: 'Release-Go-Binary'

on: 'workflow_dispatch'

jobs:
  Release-Go-Binary:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v4'
    - name: 'Build'
      uses: 'lslqtz/go-release-action@master'
      with:
        id: release
        goos: 'linux'
        goarch: 'amd64'
        goversion: 1.19
        md5sum: false
        sha256sum: false
        binary_name: 'go-testproject'
    - name: 'Echo outputs'
      run: echo ${{join(steps.run_tests.outputs.*, '\n')}}
    - name: 'Upload GitHub Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.release.outputs.RELEASE_ASSET_FILE }}
        path: ${{ steps.release.outputs.RELEASE_ASSET_PATH }}
  
