name: 'Release-Go-Binary'

on:
  workflow_dispatch:
  release:
    types: ['created']

jobs:
  Release-Go-Binary:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v4'
    - name: 'Build'
      uses: 'lslqtz/go-release-action@master'
      id: release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upload: false
        goos: 'linux'
        goarch: 'amd64'
        goversion: 1.19
        md5sum: false
        sha256sum: false
        binary_name: 'go-testproject'
        extra_files: 'README.md'
    - name: 'Upload GitHub Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-linux-arm64
        path: ${{ steps.release.outputs.release_asset_dir }}
