name: 'Release-Go-Binary'

on: 'workflow_dispatch'

jobs:
  Release-Go-Binary:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v4'
    - name: 'Build'
      uses: 'lslqtz/go-release-action@master'
      id: release
      with:
        goos: 'linux'
        goarch: 'amd64'
        goversion: 1.19
        md5sum: false
        sha256sum: false
        binary_name: 'go-testproject'
    - name: 'Echo outputs'
      run: echo ${{join(steps.release.outputs.*, '\n')}}
    - name: 'Upload GitHub Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.release.outputs.release_asset_file }}
        path: ${{ steps.release.outputs.release_asset_path }}
